services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: fraud-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - fraud-net
    restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: fraud-kafka
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: fraud-zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://fraud-kafka:29093,EXTERNAL://localhost:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - fraud-net
    restart: unless-stopped

  mlflow:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    container_name: fraud-mlflow
    command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri /app/mlruns --default-artifact-root /app/mlartifacts
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/app/mlruns
      - ./mlartifacts:/app/mlartifacts
    networks:
      - fraud-net
    restart: unless-stopped

  fastapi:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    container_name: fraud-fastapi
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 5432
      DB_NAME: frauddb
      DB_USER: postgres
      DB_PASSWORD: 030426Bc
      MLFLOW_TRACKING_URI: http://fraud-mlflow:5000
      API_KEY: mpesa-fraud-key-2026
    depends_on:
      - mlflow
    networks:
      - fraud-net
    restart: unless-stopped

  streamlit:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    container_name: fraud-streamlit
    command: streamlit run src/dashboard/app.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 5432
      DB_NAME: frauddb
      DB_USER: postgres
      DB_PASSWORD: 030426Bc
      MLFLOW_TRACKING_URI: http://fraud-mlflow:5000
      API_KEY: mpesa-fraud-key-2026
    depends_on:
      - mlflow
    networks:
      - fraud-net
    restart: unless-stopped

networks:
  fraud-net:
    driver: bridge